// qhlist1000.c

inherit SKILL;
#include <ansi.h>;

mapping *quest = ({
        ([      "quest_num":		"1",
		"quest":                "山门",
		"quest_object":		"寻衅滋事",
                "quest_place":          "山门广场",
                "file_name":            "/d/shaolin/guangchang1",
        ]),
        ([      "quest_num":		"2",
		"quest":                "钟楼",
		"quest_object":		"一探究竟",
                "quest_place":          "钟楼小院",
                "file_name":            "/d/shaolin/zhonglou",
        ]),
        ([      "quest_num":		"3",
		"quest":                "鼓楼",
		"quest_object":		"一探究竟",
                "quest_place":          "鼓楼小院",
                "file_name":            "/d/shaolin/gulou",
        ]),
        ([      "quest_num":		"4",
		"quest":                "竹林禁地",
		"quest_object":		"寻找面壁石的所在",
                "quest_place":          "初祖庵",
                "file_name":            "/d/shaolin/chuzuan",
        ]),
        ([      "quest_num":		"5",
		"quest":                "达摩院重地",
		"quest_object":		"寻衅滋事",
                "quest_place":          "达摩院",
                "file_name":            "/d/shaolin/dmyuan",
        ]),
        ([      "quest_num":		"6",
		"quest":                "藏经阁重地",
		"quest_object":		"盗取武学秘籍",
                "quest_place":          "藏经阁门口的竹林小道",
                "file_name":            "/d/shaolin/zhulin5",
        ]),
        ([      "quest_num":		"7",
		"quest":                "方丈室",
		"quest_object":		"打扰方丈清修",
                "quest_place":          "方丈楼",
                "file_name":            "/d/shaolin/fzlou",
        ]),
        ([      "quest_num":		"8",
		"quest":                "诵经堂",
		"quest_object":		"扰乱佛门清静",
                "quest_place":          "诵经堂堂前练武场",
                "file_name":            "/d/shaolin/wuchang",
        ]),
        ([      "quest_num":		"9",
		"quest":                "般若堂",
		"quest_object":		"偷学少林武技",
                "quest_place":          "般若堂",
                "file_name":            "/d/shaolin/banruo",
        ]),
        ([      "quest_num":		"10",
		"quest":                "罗汉堂",
		"quest_object":		"偷学少林武技",
                "quest_place":          "罗汉堂",
                "file_name":            "/d/shaolin/luohan",
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
