// Obj quest1.c

inherit SKILL;
#include <ansi.h>;

mapping *quest = ({
        ([      "name":                 "上太师",
                "party":                "药王谷",
                "where_place":          "/d/yaowang/huichun",
        ]),
        ([      "name":                 "刘秀才",
                "party":                "汴梁",
                "where_place":          "/d/bianliang/shuzhuang",
        ]),
        ([      "name":                 "铜人",
                "party":                "少林派",
                "where_place":          "/d/shaolin/shanmen",
        ]),
        ([      "name":                 "冉毅然",
                "party":                "汴梁",
                "where_place":          "/d/bianliang/heiyiranfang",
        ]),
        ([      "name":                 "铁心",
                "party":                "少林派",
                "where_place":          "/d/shaolin/guangchang2",
        ]), 
        ([      "name":                 "华危楼",
                "party":                "血河派",
                "where_place":          "/d/longmen/xuehepai/weitiange",
        ]),
        ([      "name":                 "曹大悲",
                "party":                "血河派",
                "where_place":          "/d/longmen/xuehepai/xueku",
        ]),
        ([      "name":                "萧萧天",
                "party":                "血河派",
                "where_place":          "/d/longmen/xuehepai/youmingge",
        ]), 
        ([      "name":                "刘亚父",
                "party":                "汴梁城",
                "where_place":          "/d/bianliang/huang_dangpu",
        ]),
        ([      "name":                "韦鸭毛",
                "party":                "汴梁",
                "where_place":          "/d/bianliang/zahuopu",
        ]),
        ([      "name":                "萘药儿",
                "party":                "药王谷",
                "where_place":          "/d/yaowang/shufang",
        ]),
        ([      "name":                "程老板",
                "party":                "权力帮",
                "where_place":          "/d/xiangyang/jyqz",
        ]), 
        ([      "name":                "叶梦色",
                "party":                "飞鱼塘",
                "where_place":          "/d/feiyu/xiwuyuan",
        ]),
        ([      "name":                "沈星南",
                "party":                "飞鱼塘",
                "where_place":          "/d/feiyu/neitang",
        ]),
        ([      "name":                "孟春花",
                "party":                "汴梁",
                "where_place":          "/d/bianliang/zaotang",
        ]), 
        ([      "name":                "祝幽",
                "party":                "天羽",
                "where_place":          "/d/tianyu/dating",
        ]),
        ([      "name":                "萧河",
                "party":                "天羽",
                "where_place":          "/d/tianyu/qixuant",
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

