// Obj quest1.c

inherit SKILL;
#include <ansi.h>;

mapping *quest = ({
        ([      "name":                 "铜智",
                "party":                "少林派",
                "where_place":          "/d/shaolin/guangchang1",
        ]),
        ([      "name":                 "铜慧",
                "party":                "少林派",
                "where_place":          "/d/shaolin/guangchang1",
        ]),
        ([      "name":                 "铜人",
                "party":                "少林派",
                "where_place":          "/d/shaolin/shanmen",
        ]),
        ([      "name":                 "铁石",
                "party":                "少林派",
                "where_place":          "/d/shaolin/guangchang2",
        ]),
        ([      "name":                 "铁心",
                "party":                "少林派",
                "where_place":          "/d/shaolin/guangchang2",
        ]), 
        ([      "name":                 "华危楼",
                "party":                "血河派",
                "where_place":          "/d/longmen/xuehepai/weitiange",
        ]),
        ([      "name":                 "曹大悲",
                "party":                "血河派",
                "where_place":          "/d/longmen/xuehepai/xueku",
        ]),
        ([      "name":                "萧萧天",
                "party":                "血河派",
                "where_place":          "/d/longmen/xuehepai/youmingge",
        ]), 
        ([      "name":                "刘亚父",
                "party":                "汴梁城",
                "where_place":          "/d/bianliang/huang_dangpu",
        ]),
         ([      "name":                "陆风",
                "party":                "药王谷",
                "where_place":          "/d/yaowang/yaowanggu",
        ]),
        ([      "name":                "萘药儿",
                "party":                "药王谷",
                "where_place":          "/d/yaowang/shufang",
        ]),
        ([      "name":                "程老板",
                "party":                "权力帮",
                "where_place":          "/d/xiangyang/jyqz",
        ]), 
        ([      "name":                "叶梦色",
                "party":                "飞鱼塘",
                "where_place":          "/d/feiyu/xiwuyuan",
        ]),
         ([     "name":                "沈星南",
                "party":                "飞鱼塘",
                "where_place":          "/d/feiyu/neitang",
        ]),
         ([     "name":                "唐讹化",
                "party":                "药王谷",
                "where_place":          "/d/yaowang/zhengting",
        ]),
         ([     "name":                "迟未",
                "party":                "药王谷",
                "where_place":          "/d/yaowang/tingyuan",
        ]),
         ([     "name":                 "郭老六",
                "party":                "药王谷",
                "where_place":          "/d/yaowang/beiting",
        ]),
          ([    "name":                "柳随风",
                "party":               "权力帮",
                "where_place":         "/d/quanli/mingge",
        ]),
         ([     "name":                 "孙人屠",
                "party":               "权力帮",
                "where_place":         "/d/quanli/huozoulang",
        ]), 
         ([     "name":                "戚常戚",
                "party":               "权力帮",
                "where_place":         "/d/quanli/xiaozoulang",
        ]),
          ([    "name":                "盛江北",
                "party":               "权力帮",
                "where_place":         "/d/quanli/xiaozoulang1",
        ]), 
/*
          ([    "name":                "王古凌",
                "party":               "权力帮",
                "where_place":         "/d/huayang/hhroad",
         ]), 
         ([    "name":                "朱若蒙",
                "party":               "权力帮",
                "where_place":         "/d/huayang/hhroad",
         ]),  
*/
          ([    "name":                "白云",
                "party":               "浣花剑派",
                "where_place":         "/d/huanhua/qianroad2",
         ]),
         ([    "name":                 "秋月",
                "party":               "浣花剑派",
                "where_place":         "/d/huanhua/tingyudoor",
         ]),
         ([    "name":                 "海神",
                "party":               "浣花剑派",
                "where_place":         "/d/huanhua/hupan_s",
         ]), 
         ([    "name":                 "燕君",
                "party":               "浣花剑派",
                "where_place":         "/d/huanhua/hupan_n",
         ]),
         ([    "name":                 "戚恋霞",
                "party":               "发梦二党",
                "where_place":         "/d/huafu/menfang",
         ]),
         ([    "name":                 "银盛雪",
                "party":               "发梦二党",
                "where_place":         "/d/huafu/dongting",
         ]),                                 
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

