mapping *skills=({                               
([	"name" : "cuff",
	"skills" : ({
                "wudang-quan",
                "luohan-quan",
                "meinu-quanfa",
                "wenjia-quan",
                "taiji-quan",
                "jingang-quan",
                "kongming-quan",
                "poyu-quan",
                "qishang-quan",
})]),
([	"name" : "strike",
	"skills" : ({
                "qingyan-zhang",
                "hamagong",
                "hanbing-mianzhang",
                "sanhua-zhang",
                "weituo-zhang",
                "luoying-zhang",
                "banruo-zhang",
                "chousui-zhang",
                "hunyuan-zhang",
                "sixiang-zhang",
                "xianglong-zhang",
})
]),	
([	"name" : "hand",
	"skills" : ({
                "fengyun-shou",
                "yingzhua-shou",
                "suohou-shou",
                "jieshou-jiushi",
                "juehu-shou",
                "lanhua-shou",
                "qianye-shou",
})]),
([/*leg*/"name" : "leg",
	"skills" : ({
                "shaolin-tantui",
                "ruying-suixingtui",
                "xuanfeng-tui",
})]),
([/*finger*/"name" : "finger",
	 "skills" : ({
                "mohe-zhi",
                "qianzhu-wandushou",
                "nianhua-zhi",
                "yiyang-zhi",
                "yizhi-chan",
                "tanzhi-shentong",
})]),
([/*claw*/"name" : "claw",
	"skills" : ({
                "yingzhua-gong",
                "jimie-zhua",
                "longzhua-gong",
})]),
([/*blade*/"name" : "blade",
	"skills" : ({
                "xuanxu-daofa",
                "shenghuo-lingfa",
                "yanxing-daofa",
                "wenjia-daofa",
                "lieyan-dao",
                "xiuluo-dao",
                "liuhe-daofa",
                "ranmu-daofa",
                "cibei-dao",
                "fanliangyi-dao",
})]),
([/*sword*/"name" : "sword",
	"skills" : ({
		"damo-jian",
	        "quanzhen-jianfa",
                "fumo-jian",
                "huifeng-jian",
                "yunu-jianfa",
                "yuxiao-jian",
	    	"duanjia-jianfa",
	        "liehuo-jian",
		"taiji-jian",
		"jinshe-jianfa",
		"xuantie-jianfa",
		"huashan-jianfa",
})]),
([/*club*/"name" : "club",
	"skills" : ({
                "weituo-gun",
		"zui-gun",
})]),
([/*staff*/"name" : "staff",
	"skills" : ({                                           
                "pudu-zhang",
		"baituo-shezhang",
		"fengmo-zhang",
		"wuchang-zhang",
		"tianshan-zhang",
})]),
([/*whip*/"name" : "whip",
	"skills" : ({
                "yuxu-bian",
                "qingxu-bian",
                "huifeng-bian",
                "riyue-bian",
})]),
([/*stick*/"name" : "stick",
	"skills" : ({
                "dagou-bang",
})]),
});